### ISSUE TITLE
Requirement Analysis

### ISSUE THREAD

**Issue by oncelkeles** [oncelkeles/purposeful-community#4]
**Description**
Requirement Analysis should be made in order to move forward with the project with design structures.

**Comment by oncelkeles** [comment]
The draft can be reached from [this document](https://docs.google.com/document/d/1dfP__b7_HpOm-_EKIE0EGpca_t52jEif2VGhoQuUs28/edit?usp=sharing).

**Comment by alperenkozkan** [comment]
Requirements should be refined and wiki page should be created from refined draft document.

**Comment by oncelkeles** [comment]
First draft of requirements are added to the wiki. However, there are some things we should consider regarding our meeting on the requirements:

- **Sub-communities**: To distinguish topic of interest of different communities
- **User roles in sub-communities**: organizer/admin, normal etc.
- **Post type creation for admin/organizer user roles**: To enable user defined post types according to the community needs
